// src/store/actions.js
/**
 * Action type constants for App Store (Reducer)
 * เป้าหมาย:
 * - รวม action ทั้งหมดไว้จุดเดียว ป้องกันพิมพ์ผิด/ชื่อไม่ตรงกัน
 * - ทำให้ state transitions ของแอพ “สอดคล้องกัน” และ debug ง่าย
 *
 * NOTE:
 * - ไฟล์นี้ไม่มีเรื่อง UX/UI โดยตรง แต่เป็นแกนสำคัญให้ app ทำงานถูกต้อง
 * - โครงสร้างนี้รองรับการขยายในอนาคต (เช่น UPDATE_CATEGORY, SET_UI ฯลฯ) ได้ง่าย
 */

export const ACTIONS = Object.freeze({
  // boot / navigation
  INIT: "INIT",
  NAVIGATE: "NAVIGATE",

  // transactions
  START_NEW_TRANSACTION: "START_NEW_TRANSACTION",
  START_EDIT_TRANSACTION: "START_EDIT_TRANSACTION",
  UPSERT_TRANSACTION: "UPSERT_TRANSACTION",
  BULK_UPSERT_TRANSACTIONS: "BULK_UPSERT_TRANSACTIONS",
  DELETE_TRANSACTION: "DELETE_TRANSACTION",
  DELETE_MANY_TRANSACTIONS: "DELETE_MANY_TRANSACTIONS",

  // accounts
  ADD_ACCOUNT: "ADD_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",

  // categories
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  // budgets
  UPSERT_BUDGET: "UPSERT_BUDGET",
  DELETE_BUDGET: "DELETE_BUDGET",

  // recurring
  UPSERT_RECURRING: "UPSERT_RECURRING",
  DELETE_RECURRING: "DELETE_RECURRING",
  APPLY_RECURRING_GENERATION: "APPLY_RECURRING_GENERATION",

  // scan inbox
  SCAN_INBOX_ADD_MANY: "SCAN_INBOX_ADD_MANY",
  SCAN_INBOX_REMOVE: "SCAN_INBOX_REMOVE",
  SCAN_INBOX_CLEAR: "SCAN_INBOX_CLEAR",

  // inbox (pending/approved)
  INBOX_UPSERT_MANY: "INBOX_UPSERT_MANY",
  INBOX_UPDATE_ONE: "INBOX_UPDATE_ONE",
  INBOX_REMOVE_MANY: "INBOX_REMOVE_MANY",
  INBOX_CLEAR_APPROVED: "INBOX_CLEAR_APPROVED",
  INBOX_CLEAR_ALL: "INBOX_CLEAR_ALL",

  // automation rules
  RULE_UPSERT: "RULE_UPSERT",
  RULE_UPDATE: "RULE_UPDATE",
  RULE_DELETE: "RULE_DELETE",
  RULE_SET_ORDER: "RULE_SET_ORDER",

  // Smart Merchant Dictionary
  MERCHANT_UPSERT: "MERCHANT_UPSERT",
  MERCHANT_UPDATE: "MERCHANT_UPDATE",
  MERCHANT_DELETE: "MERCHANT_DELETE",
  MERCHANT_MERGE: "MERCHANT_MERGE",
  MERCHANT_LEARN: "MERCHANT_LEARN",

  // reset/import
  RESET_ALL: "RESET_ALL",
  IMPORT_BACKUP: "IMPORT_BACKUP",
});
