// src/store/actions.js

export const ACTIONS = {
  INIT: "INIT",
  NAVIGATE: "NAVIGATE",

  START_NEW_TRANSACTION: "START_NEW_TRANSACTION",
  START_EDIT_TRANSACTION: "START_EDIT_TRANSACTION",

  UPSERT_TRANSACTION: "UPSERT_TRANSACTION",
  DELETE_TRANSACTION: "DELETE_TRANSACTION",

  // ✅ Transfer (เป็นชุด 2 รายการ)
  UPSERT_TRANSFER: "UPSERT_TRANSFER",
  DELETE_TRANSFER_GROUP: "DELETE_TRANSFER_GROUP",

  ADD_ACCOUNT: "ADD_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",

  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  RESET_ALL: "RESET_ALL",
  IMPORT_BACKUP: "IMPORT_BACKUP",
};
