// src/store/actions.js
export const ACTIONS = {
  INIT: "INIT",
  NAVIGATE: "NAVIGATE",

  START_NEW_TRANSACTION: "START_NEW_TRANSACTION",
  START_EDIT_TRANSACTION: "START_EDIT_TRANSACTION",

  UPSERT_TRANSACTION: "UPSERT_TRANSACTION",
  BULK_UPSERT_TRANSACTIONS: "BULK_UPSERT_TRANSACTIONS",
  DELETE_TRANSACTION: "DELETE_TRANSACTION",

  ADD_ACCOUNT: "ADD_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",

  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  UPSERT_BUDGET: "UPSERT_BUDGET",
  DELETE_BUDGET: "DELETE_BUDGET",

  UPSERT_RECURRING: "UPSERT_RECURRING",
  DELETE_RECURRING: "DELETE_RECURRING",
  APPLY_RECURRING_GENERATION: "APPLY_RECURRING_GENERATION",

  RESET_ALL: "RESET_ALL",
  IMPORT_BACKUP: "IMPORT_BACKUP",
};
