create table if not exists public.planner_monthly_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month_key text not null check (month_key ~ '^\d{4}-\d{2}$'),
  scenario_key text not null check (scenario_key in ('baseline', 'tight', 'comfort')),
  status text not null default 'draft' check (status in ('draft', 'applied', 'archived')),
  engine_version text not null,
  income_basis_satang integer not null default 0,
  savings_reserve_satang integer not null default 0,
  debt_minimum_satang integer not null default 0,
  available_expense_satang integer not null default 0,
  recommended_expense_satang integer not null default 0,
  shortfall_satang integer not null default 0,
  confidence_score numeric(5,4) not null default 0,
  generated_at timestamptz not null default timezone('utc', now()),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, month_key, scenario_key)
);

create table if not exists public.planner_monthly_plan_items (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.planner_monthly_plans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  month_key text not null check (month_key ~ '^\d{4}-\d{2}$'),
  scenario_key text not null check (scenario_key in ('baseline', 'tight', 'comfort')),
  category_id text not null,
  behavior text not null check (behavior in ('fixed', 'essential', 'flexible')),
  baseline_spend_satang integer not null default 0,
  recent_spend_satang integer not null default 0,
  current_pace_satang integer not null default 0,
  volatility_score numeric(5,4) not null default 0,
  recommended_limit_satang integer not null default 0,
  delta_satang integer not null default 0,
  confidence_score numeric(5,4) not null default 0,
  reason_codes jsonb not null default '[]'::jsonb,
  locked_by_user boolean not null default false,
  decision_status text not null default 'pending' check (decision_status in ('pending', 'accepted', 'dismissed')),
  applied_limit_satang integer not null default 0,
  locked_limit_satang integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, month_key, scenario_key, category_id)
);

create index if not exists planner_monthly_plans_user_month_idx
  on public.planner_monthly_plans (user_id, month_key, scenario_key);

create index if not exists planner_monthly_plan_items_user_month_idx
  on public.planner_monthly_plan_items (user_id, month_key, scenario_key);

create index if not exists planner_monthly_plan_items_plan_idx
  on public.planner_monthly_plan_items (plan_id);

alter table public.planner_monthly_plans enable row level security;
alter table public.planner_monthly_plan_items enable row level security;

drop policy if exists "planner monthly plans select own" on public.planner_monthly_plans;
create policy "planner monthly plans select own"
  on public.planner_monthly_plans
  for select
  using (auth.uid() = user_id);

drop policy if exists "planner monthly plans insert own" on public.planner_monthly_plans;
create policy "planner monthly plans insert own"
  on public.planner_monthly_plans
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "planner monthly plans update own" on public.planner_monthly_plans;
create policy "planner monthly plans update own"
  on public.planner_monthly_plans
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "planner monthly plans delete own" on public.planner_monthly_plans;
create policy "planner monthly plans delete own"
  on public.planner_monthly_plans
  for delete
  using (auth.uid() = user_id);

drop policy if exists "planner monthly plan items select own" on public.planner_monthly_plan_items;
create policy "planner monthly plan items select own"
  on public.planner_monthly_plan_items
  for select
  using (auth.uid() = user_id);

drop policy if exists "planner monthly plan items insert own" on public.planner_monthly_plan_items;
create policy "planner monthly plan items insert own"
  on public.planner_monthly_plan_items
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "planner monthly plan items update own" on public.planner_monthly_plan_items;
create policy "planner monthly plan items update own"
  on public.planner_monthly_plan_items
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "planner monthly plan items delete own" on public.planner_monthly_plan_items;
create policy "planner monthly plan items delete own"
  on public.planner_monthly_plan_items
  for delete
  using (auth.uid() = user_id);
